apiVersion: v1
kind: Service
metadata:
  name: findzone-service
  labels:
    app: fe-findzone
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    app: fe-findzone
  type: LoadBalancer