name: Build and Deploy to GKE

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: 
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  IMAGE: ${{ secrets.IMAGE }}
  REGISTRY_HOSTNAME: ${{ secrets.REGISTRY_HOSTNAME }}
  DEPLOYMENT_NAME: ${{ secrets.DEPLOYMENT_NAME }}
  SERVER: ${{ secrets.REACT_APP_SERVER }}
  NAVER_MAP_KEY: ${{ secrets.REACT_APP_NAVER_MAP_KEY }}

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    # set .env value
    - name: set .env.* file
      run: |
        sed -i "1s/=/&aaaaaa/" .env.production
        sed -i "2s/=/&$bbbbbb/" .env.production
        cat .env.production